package com.dbapp.springmvc.mapper;

import com.dbapp.springmvc.pojo.Items;
import com.dbapp.springmvc.pojo.ItemsCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * MyBatis Mapper 接口 - 表：items
 * @since 2017-09-21 15:19:57
 */
public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int countByExample(ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int deleteByExample(ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    List<Items> selectByExampleWithBLOBs(ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    List<Items> selectByExample(ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    Items selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Items record, @Param("example") ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByExample(@Param("record") Items record, @Param("example") ItemsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByPrimaryKeySelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Thu Sep 21 15:19:57 CST 2017
     */
    int updateByPrimaryKey(Items record);
}